name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install-depends
      run: sudo apt install -y g++-12-riscv64-linux-gnu
    - name: build
      run: |
        g++ -o ringbuffer_amd64 ringbuffer.cpp
        riscv64-linux-gnu-g++-12 -o ringbuffer_riscv64 ringbuffer.cpp
    - name: upload-binary-amd64
      uses: actions/upload-artifact@v4
      with:
        name: ringbuffer-binary-amd64
        path: ringbuffer_amd64
    - name: upload-binary-riscv64
      uses: actions/upload-artifact@v4
      with:
        name: ringbuffer-binary-riscv64
        path: ringbuffer_riscv64
